# -*- coding: utf-8 -*-
"""Project509

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZYebp5oAP0B1wxigrV2IK5CNMBNB791
"""

# Step 1: Install required packages
!pip install kaggle tensorflow opencv-python split-folders

import os
import shutil
import numpy as np
import splitfolders
import tensorflow as tf
from tensorflow.keras import layers, models
import cv2
from google.colab import files  # Remove if not using Colab

# Step 2: Kaggle API Setup (Upload your kaggle.json first if using Colab)
# Upload kaggle.json (only needed for Colab)
files.upload()  # Remove this if not using Colab

# Create kaggle directory and set permissions
os.makedirs('/root/.kaggle', exist_ok=True)
shutil.move('kaggle.json', '/root/.kaggle/')
os.chmod('/root/.kaggle/kaggle.json', 600)

# Step 3: Download and Extract Dataset
!kaggle datasets download -d ninadaithal/imagesoasis
!unzip -q imagesoasis.zip -d oasis_data

# Step 4: Organize Data into Class Folders
# (Assuming you have class labels from another source/metadata)
# This part is CRUCIAL - ADAPT based on your actual class labels!
# ---------------------------------------------------------------
# Create temporary directory structure
base_dir = 'organized_data'
os.makedirs(base_dir, exist_ok=True)

# Get list of images and masks
image_dir = 'oasis_data/images'
mask_dir = 'oasis_data/masks'

# This is placeholder logic - REPLACE with your actual class labeling strategy!
# Example: Create 4 artificial classes based on mask characteristics
class_names = ['class0', 'class1', 'class2', 'class3']

for cls in class_names:
    os.makedirs(os.path.join(base_dir, cls), exist_ok=True)

# Dummy classification: Assign classes based on mask pixel averages
# THIS IS JUST AN EXAMPLE - USE REAL LABELS HERE!
for img_file in os.listdir(image_dir):
    if img_file.endswith('.png'):
        # Load corresponding mask
        mask_path = os.path.join(mask_dir, img_file)
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)

        # Fake class assignment based on mask properties
        mean_val = np.mean(mask)
        cls_idx = min(int(mean_val // 64), 3)  # Creates 4 classes
        dest_dir = os.path.join(base_dir, class_names[cls_idx])

        # Copy image to class directory
        shutil.copy(os.path.join(image_dir, img_file), dest_dir)

# Step 5: Split Data into Train/Test
splitfolders.ratio(
    base_dir,
    output="final_data",
    seed=42,
    ratio=(0.7, 0.3),
    group_prefix=None
)

# Step 6: Create Data Generators
train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    'final_data/train',
    target_size=(256, 256),
    batch_size=32,
    class_mode='categorical'
)

test_generator = test_datagen.flow_from_directory(
    'final_data/val',  # splitfolders uses 'val' for test
    target_size=(256, 256),
    batch_size=32,
    class_mode='categorical',
    shuffle=False
)

# Step 7: Build CNN Model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(4, activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Step 8: Train Model
history = model.fit(
    train_generator,
    epochs=15,
    validation_data=test_generator
)

# Step 9: Evaluate
test_loss, test_acc = model.evaluate(test_generator)
print(f'\nTest accuracy: {test_acc:.4f}')

# Save model
model.save('mri_classifier.h5')

# ========================================
# STEP 1: Install & Configure Kaggle CLI
# ========================================
!pip install -q kaggle

# Create a directory for the Kaggle config and move the API token there.
# NOTE: You will be prompted to upload kaggle.json from your local machine.
import os
os.environ['KAGGLE_CONFIG_DIR'] = '/content'
!mkdir -p /root/.kaggle
!cp /content/kaggle.json /root/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

# ========================================
# STEP 2: Download the dataset from Kaggle
# ========================================
!kaggle datasets download ninadaithal/imagesoasis --force -p /content

# Unzip the downloaded dataset
!unzip -q /content/imagesoasis.zip -d /content/images_oasis

# After unzipping, you should see the following folder structure:
#   images_oasis/
#       Mild Dementia/
#       Moderate Dementia/
#       Non Demented/
#       Very Mild Dementia/



##############################################
# STEP 1: Install & Configure Kaggle CLI
##############################################
!pip install -q kaggle

import os

# Point Kaggle to /content for config
os.environ["KAGGLE_CONFIG_DIR"] = "/content"

# Create a ~/.kaggle folder
!mkdir -p ~/.kaggle

# Upload your kaggle.json file (from Kaggle > Account > API)
from google.colab import files
uploaded = files.upload()  # select kaggle.json

# Move the kaggle.json into your ~/.kaggle folder
!cp /content/kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

##############################################
# STEP 2: Download & Unzip the Dataset
##############################################
# This example uses the "Images Oasis" Kaggle dataset as a placeholder.
# Replace 'ninadaithal/imagesoasis' with your exact dataset if different.
!kaggle datasets download ninadaithal/imagesoasis -p /content --force

# Unzip into /content/Data (assuming the ZIP contains a folder named "Data" with 4 subfolders)
!unzip -q /content/imagesoasis.zip -d /content

# You should now have a structure like:
# /content/Data/
#   Mild Dementia/
#   Moderate Dementia/
#   Non Demented/
#   Very Mild Dementia/
#
# Each folder has a set of slices for various patients, e.g.:
#   OAS1_0285_MR1_mpr-1_128.jpg

##############################################
# STEP 3: (Optional) Inspect & Compare Slice Indices
##############################################
import re

# Example code showing how to parse the slice index from a filename:
slice_pattern = re.compile(r".*_(\d+)\.jpg$")

data_root = "/content/Data"
classes = ["Mild Dementia", "Moderate Dementia", "Non Demented", "Very mild Dementia"]

for cls in classes:
    cls_path = os.path.join(data_root, cls)
    filenames = os.listdir(cls_path)
    for fname in filenames[:5]:  # just look at first 5 for demonstration
        match = slice_pattern.match(fname)
        if match:
            slice_idx = int(match.group(1))
            print(f"Class={cls} | Filename={fname} | SliceIndex={slice_idx}")
    print("----")

# The above snippet shows how you might detect that, say, "OAS1_0285_MR1_mpr-1_128.jpg"
# has a slice index of 128. You can use this logic to group or compare slice #100 vs. #100
# from other patients, if you wish.

##############################################
# STEP 4: Split the Data into Train/Test (70:30)
##############################################
import shutil, random

base_dir = "/content/OASIS_split"
train_dir = os.path.join(base_dir, "train")
test_dir  = os.path.join(base_dir, "test")

os.makedirs(train_dir, exist_ok=True)
os.makedirs(test_dir, exist_ok=True)

for cls in classes:
    cls_folder = os.path.join(data_root, cls)
    all_images = os.listdir(cls_folder)
    random.shuffle(all_images)

    # 70:30 split
    split_idx = int(0.7 * len(all_images))
    train_imgs = all_images[:split_idx]
    test_imgs  = all_images[split_idx:]

    # Make subfolders
    os.makedirs(os.path.join(train_dir, cls), exist_ok=True)
    os.makedirs(os.path.join(test_dir, cls), exist_ok=True)

    # Copy the files
    for img_name in train_imgs:
        src = os.path.join(cls_folder, img_name)
        dst = os.path.join(train_dir, cls, img_name)
        shutil.copy2(src, dst)

    for img_name in test_imgs:
        src = os.path.join(cls_folder, img_name)
        dst = os.path.join(test_dir, cls, img_name)
        shutil.copy2(src, dst)

print("Data split complete.")
print("Train folder:", train_dir)
print("Test folder:", test_dir)

##############################################
# STEP 5: Keras ImageDataGenerators
##############################################
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = (150, 150)
BATCH_SIZE = 32

# Training generator with augmentations
train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    rotation_range=20,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

# Testing generator (just rescale)
test_datagen = ImageDataGenerator(rescale=1.0/255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False  # keep ordering consistent
)

##############################################
# STEP 6: Build a CNN Model
##############################################
from tensorflow.keras import layers, models

model = models.Sequential()

# Conv-Pool Block 1
model.add(layers.Conv2D(32, (3,3), activation='relu', input_shape=(150,150,3)))
model.add(layers.MaxPooling2D((2,2)))

# Conv-Pool Block 2
model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

# Conv-Pool Block 3
model.add(layers.Conv2D(128, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

# Flatten + Dense
model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dropout(0.3))
model.add(layers.Dense(4, activation='softmax'))  # 4 classes

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

##############################################
# STEP 7: Train the Model
##############################################
EPOCHS = 1
history = model.fit(
    train_generator,
    epochs=EPOCHS,
    validation_data=test_generator
)

##############################################
# STEP 8: Evaluate & Visualize Results
##############################################
import matplotlib.pyplot as plt

acc     = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss    = history.history['loss']
val_loss= history.history['val_loss']
epochs_range = range(EPOCHS)

# Plot Accuracy
plt.figure()
plt.plot(epochs_range, acc, label='Train Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.title('Training & Validation Accuracy')
plt.legend()
plt.show()

# Plot Loss
plt.figure()
plt.plot(epochs_range, loss, label='Train Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.title('Training & Validation Loss')
plt.legend()
plt.show()

# Final Test Eval
test_loss, test_accuracy = model.evaluate(test_generator, verbose=1)
print(f"Test Accuracy: {test_accuracy:.4f}")
print(f"Test Loss:     {test_loss:.4f}")

print("Class Indices:", train_generator.class_indices)

##############################################
# STEP 9: (Optional) Inspect Predictions
##############################################
import numpy as np

test_generator.reset()
preds = model.predict(test_generator)
predicted_class_indices = np.argmax(preds, axis=1)

print("\nFirst 5 predicted class indices:", predicted_class_indices[:5])